// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Screen2, &ui_img_1781425391, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chatgpt = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_chatgpt);
    lv_obj_set_width(ui_chatgpt, 60);
    lv_obj_set_height(ui_chatgpt, 75);
    lv_obj_set_x(ui_chatgpt, 45);
    lv_obj_set_y(ui_chatgpt, 36);
    lv_obj_clear_flag(ui_chatgpt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_chatgpt);
    lv_img_set_src(ui_Image1, &ui_img_gpt_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_chatgpt);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, 60);
    lv_obj_set_align(ui_Label1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label1, "chatgpt");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_sc1d, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setting = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_setting);
    lv_obj_set_width(ui_setting, 60);
    lv_obj_set_height(ui_setting, 75);
    lv_obj_set_x(ui_setting, 130);
    lv_obj_set_y(ui_setting, 36);
    lv_obj_clear_flag(ui_setting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_setting);
    lv_img_set_src(ui_Image4, &ui_img_349290311);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image4, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_setting);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, 60);
    lv_obj_set_align(ui_Label3, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label3, "设置");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_sc1d, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clockSet = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_clockSet);
    lv_obj_set_width(ui_clockSet, 60);
    lv_obj_set_height(ui_clockSet, 75);
    lv_obj_set_x(ui_clockSet, 215);
    lv_obj_set_y(ui_clockSet, 36);
    lv_obj_clear_flag(ui_clockSet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_clockSet);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, 60);
    lv_obj_set_align(ui_Label4, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label4, "闹钟");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_sc1d, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton1 = lv_imgbtn_create(ui_clockSet);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_605947028, NULL);
    lv_obj_set_height(ui_ImgButton1, 64);
    lv_obj_set_width(ui_ImgButton1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_ImgButton1, LV_ALIGN_CENTER);

    ui_weatherDisplay = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_weatherDisplay);
    lv_obj_set_width(ui_weatherDisplay, 60);
    lv_obj_set_height(ui_weatherDisplay, 75);
    lv_obj_set_x(ui_weatherDisplay, 45);
    lv_obj_set_y(ui_weatherDisplay, 127);
    lv_obj_clear_flag(ui_weatherDisplay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_img_create(ui_weatherDisplay);
    lv_img_set_src(ui_Image6, &ui_img_942592375);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image6, 0);
    lv_obj_set_y(ui_Image6, 10);
    lv_obj_set_align(ui_Image6, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_weatherDisplay);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, 60);
    lv_obj_set_align(ui_Label5, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label5, "天气");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_sc1d, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempAndHum = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_tempAndHum);
    lv_obj_set_width(ui_tempAndHum, 60);
    lv_obj_set_height(ui_tempAndHum, 75);
    lv_obj_set_x(ui_tempAndHum, 130);
    lv_obj_set_y(ui_tempAndHum, 127);
    lv_obj_clear_flag(ui_tempAndHum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_img_create(ui_tempAndHum);
    lv_img_set_src(ui_Image7, &ui_img_656870604);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image7, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_tempAndHum);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, 60);
    lv_obj_set_align(ui_Label6, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label6, "温湿度");
    lv_obj_set_style_text_font(ui_Label6, &ui_font_sc1d, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButton1, ui_event_ImgButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}
