// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image2, &ui_img_284269679);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_date = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date, 10);
    lv_obj_set_y(ui_date, -97);
    lv_obj_set_align(ui_date, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_date, "23/12/05");
    lv_obj_set_style_text_font(ui_date, &ui_font_sc1c, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temperature = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_temperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperature, -5);
    lv_obj_set_y(ui_temperature, -97);
    lv_obj_set_align(ui_temperature, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_temperature, "12-25");
    lv_obj_set_style_text_font(ui_temperature, &ui_font_sc1c, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_weather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weather, -10);
    lv_obj_set_y(ui_weather, -60);
    lv_obj_set_align(ui_weather, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_weather, "晴");
    lv_obj_set_style_text_font(ui_weather, &ui_font_sc1c, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clock = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_clock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_clock, 0);
    lv_obj_set_y(ui_clock, 99);
    lv_obj_set_align(ui_clock, LV_ALIGN_CENTER);
    lv_label_set_text(ui_clock, "15:32的时候别忘了出门");
    lv_obj_set_style_text_font(ui_clock, &ui_font_sc1d, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, 5);
    lv_obj_set_y(ui_time, -63);
    lv_obj_set_align(ui_time, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_time, "15:08");
    lv_obj_set_style_text_font(ui_time, &ui_font_sc1a, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
