// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Screen3, &ui_img_1781425391, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel1, 260);
    lv_obj_set_height(ui_Panel1, 40);
    lv_obj_set_x(ui_Panel1, 1);
    lv_obj_set_y(ui_Panel1, -68);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 25);
    lv_obj_set_y(ui_Label2, 0);
    lv_obj_set_align(ui_Label2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label2, "15:20");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_sc1d, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 75);
    lv_obj_set_y(ui_Label7, 0);
    lv_obj_set_align(ui_Label7, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label7, "写作业");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_sc1d, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_Panel1);
    lv_obj_set_width(ui_Switch1, 40);
    lv_obj_set_height(ui_Switch1, 20);
    lv_obj_set_x(ui_Switch1, 10);
    lv_obj_set_y(ui_Switch1, 0);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_RIGHT_MID);


    ui_Image8 = lv_img_create(ui_Panel1);
    lv_img_set_src(ui_Image8, &ui_img_1061045036);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image8, -10);
    lv_obj_set_y(ui_Image8, 0);
    lv_obj_set_align(ui_Image8, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton2 = lv_imgbtn_create(ui_Screen3);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1888461063, NULL);
    lv_obj_set_height(ui_ImgButton2, 30);
    lv_obj_set_width(ui_ImgButton2, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_x(ui_ImgButton2, -110);
    lv_obj_set_y(ui_ImgButton2, 83);
    lv_obj_set_align(ui_ImgButton2, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ImgButton2, ui_event_ImgButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen3, ui_event_Screen3, LV_EVENT_ALL, NULL);

}
