// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Keyboard1 = lv_keyboard_create(ui_Screen4);
    lv_obj_set_width(ui_Keyboard1, 300);
    lv_obj_set_height(ui_Keyboard1, 120);
    lv_obj_set_x(ui_Keyboard1, 2);
    lv_obj_set_y(ui_Keyboard1, 59);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    ui_Label8 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 8);
    lv_obj_set_y(ui_Label8, 13);
    lv_label_set_text(ui_Label8, "时间");
    lv_obj_set_style_text_font(ui_Label8, &ui_font_sc1d, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea2 = lv_textarea_create(ui_Screen4);
    lv_obj_set_width(ui_TextArea2, 182);
    lv_obj_set_height(ui_TextArea2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_TextArea2, 40);
    lv_obj_set_y(ui_TextArea2, 5);
    lv_textarea_set_max_length(ui_TextArea2, 16);
    lv_textarea_set_one_line(ui_TextArea2, true);
    lv_obj_set_style_text_font(ui_TextArea2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Label9 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 8);
    lv_obj_set_y(ui_Label9, 53);
    lv_label_set_text(ui_Label9, "备注");
    lv_obj_set_style_text_font(ui_Label9, &ui_font_sc1d, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea3 = lv_textarea_create(ui_Screen4);
    lv_obj_set_width(ui_TextArea3, 270);
    lv_obj_set_height(ui_TextArea3, 70);
    lv_obj_set_x(ui_TextArea3, 40);
    lv_obj_set_y(ui_TextArea3, 45);
    lv_textarea_set_max_length(ui_TextArea3, 128);
    lv_obj_set_style_text_font(ui_TextArea3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_ImgButton3 = lv_imgbtn_create(ui_Screen4);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1583546726, NULL);
    lv_obj_set_height(ui_ImgButton3, 30);
    lv_obj_set_width(ui_ImgButton3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton3, -40);
    lv_obj_set_y(ui_ImgButton3, 7);
    lv_obj_set_align(ui_ImgButton3, LV_ALIGN_TOP_RIGHT);

    ui_ImgButton4 = lv_imgbtn_create(ui_Screen4);
    lv_imgbtn_set_src(ui_ImgButton4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1918843369, NULL);
    lv_obj_set_height(ui_ImgButton4, 31);
    lv_obj_set_width(ui_ImgButton4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton4, -5);
    lv_obj_set_y(ui_ImgButton4, 5);
    lv_obj_set_align(ui_ImgButton4, LV_ALIGN_TOP_RIGHT);

    lv_obj_add_event_cb(ui_ImgButton4, ui_event_ImgButton4, LV_EVENT_ALL, NULL);

}
