// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
void sc1_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_date;
extern lv_obj_t * ui_temperature;
extern lv_obj_t * ui_weather;
extern lv_obj_t * ui_clock;
extern lv_obj_t * ui_time;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_chatgpt;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_setting;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_clockSet;
extern lv_obj_t * ui_Label4;
void ui_event_ImgButton1(lv_event_t * e);
extern lv_obj_t * ui_ImgButton1;
extern lv_obj_t * ui_weatherDisplay;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_tempAndHum;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Label6;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Image8;
void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_TextArea3;
extern lv_obj_t * ui_ImgButton3;
void ui_event_ImgButton4(lv_event_t * e);
extern lv_obj_t * ui_ImgButton4;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_284269679);    // assets\图层 3.png
LV_IMG_DECLARE(ui_img_1781425391);    // assets\应用界面背景.png
LV_IMG_DECLARE(ui_img_gpt_png);    // assets\gpt.png
LV_IMG_DECLARE(ui_img_349290311);    // assets\设置_填充.png
LV_IMG_DECLARE(ui_img_605947028);    // assets\闹钟.png
LV_IMG_DECLARE(ui_img_942592375);    // assets\天气.png
LV_IMG_DECLARE(ui_img_656870604);    // assets\温湿度_高温.png
LV_IMG_DECLARE(ui_img_1061045036);    // assets\减30.png
LV_IMG_DECLARE(ui_img_1888461063);    // assets\增加30.png
LV_IMG_DECLARE(ui_img_1583546726);    // assets\正确30.png
LV_IMG_DECLARE(ui_img_1918843369);    // assets\取消30.png

LV_FONT_DECLARE(ui_font_sc1a);
LV_FONT_DECLARE(ui_font_sc1c);
LV_FONT_DECLARE(ui_font_sc1d);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
